export const quotes = [
  `Success doesn’t happen overnight; it’s the result of small consistent efforts that compound over time. Every day you wake up and decide to give your best, even when motivation fades, you build a stronger version of yourself. The truth is, progress is often invisible. You may not notice the small changes, but they’re shaping the foundation of your future. The key is to stay patient and disciplined, to focus on the process rather than the outcome. Remember that failure is not the opposite of success, it’s part of the journey. Every mistake teaches you something valuable. So don’t rush your growth; give yourself time, space, and grace. Keep showing up, even when results aren’t immediate, because consistency will eventually make you unstoppable.`,

  `Technology is changing the world faster than we can imagine. What was impossible a decade ago is now part of everyday life. Artificial intelligence, automation, and data-driven decisions are shaping industries across the globe. But beyond innovation, technology is about solving human problems—making life easier, smarter, and more connected. The real challenge is using technology responsibly, ensuring it empowers rather than replaces. The most successful people in tech are not just coders or engineers; they are problem solvers, thinkers, and dreamers who see possibilities where others see limits. The future belongs to those who learn continuously and adapt quickly.`,

  `Creativity isn’t limited to artists, writers, or designers; it’s a skill that every person can develop. Being creative means thinking differently, questioning the usual way of doing things, and exploring what others might overlook. The mind becomes more creative when it’s curious, rested, and unafraid of failure. True creativity often emerges from boredom or frustration—it’s a spark that turns problems into opportunities. To be creative, you don’t need perfect conditions; you just need courage to start. Every new idea begins as a simple thought, so nurture your imagination, let it breathe, and see where it takes you.`,

  `Discipline often beats talent. While natural ability can give you a head start, it’s discipline that keeps you moving when excitement fades. Successful people aren’t always the smartest or most gifted; they’re the ones who keep going when others quit. Discipline is about doing what needs to be done, even when you don’t feel like it. It’s about mastering your habits, managing your time, and being consistent in your actions. The small, boring steps are what build greatness. When you learn to control your impulses, focus on long-term goals, and push through discomfort, you realize that success was never about luck—it was about persistence.`,

  `In life, perspective is everything. Two people can experience the same event and walk away with entirely different lessons. The difference lies in how they choose to see things. Challenges can either break you or shape you depending on your mindset. When you start viewing failures as feedback and obstacles as opportunities, everything changes. You stop fearing problems and start solving them. The world rewards those who stay optimistic even in chaos because positivity sharpens creativity. No one can control what happens to them, but everyone can control how they respond—and that choice defines your growth.`,

  `Learning is a lifelong journey, not a destination. The most successful individuals never stop learning because they understand that knowledge evolves faster than ever. Reading books, experimenting with new ideas, and engaging with people from different backgrounds expand your thinking. Curiosity fuels progress, and humility keeps you teachable. The moment you think you know everything is the moment growth stops. Instead of chasing perfection, focus on continuous improvement. Every new skill you learn compounds your value. In a rapidly changing world, your ability to learn, unlearn, and relearn is your greatest superpower.`,

  `Productivity is not about doing more; it’s about doing what truly matters. Many people fill their schedules with tasks that don’t move them closer to their goals. True productivity begins with clarity—knowing what’s important and eliminating distractions. It’s about managing your energy, not just your time. Rest, reflection, and breaks are part of being productive. When you work with focus and purpose, you achieve better results in less time. Remember, busyness doesn’t equal progress. Be intentional about your actions, and success will follow naturally.`,

  `Self-confidence isn’t built by affirmations alone; it’s forged through action. Every time you do something uncomfortable, you prove to yourself that you’re capable. Confidence grows when you keep promises you make to yourself. It’s not about arrogance or perfection; it’s about trust in your own ability to handle life. You don’t need approval from everyone—you need belief in yourself. The more challenges you face and overcome, the stronger that belief becomes. With time, confidence stops being something you chase; it becomes part of who you are.`,

  `Patience is one of the hardest skills to master in the modern world. We live in an age of instant results—instant food, instant messages, instant gratification. But real success takes time. The seed doesn’t sprout the moment it’s planted. You have to water it, protect it, and wait for it to grow. Impatience leads to shortcuts, and shortcuts often cost more than they save. Patience teaches you resilience, focus, and emotional control. The most beautiful things in life unfold slowly; all you need is faith in the process and consistency in your effort.`,

  `Failure isn’t the end of the road—it’s a redirection. Every person who has achieved something great has failed more times than they’ve succeeded. What sets them apart is their attitude toward failure. They don’t see it as proof of weakness but as evidence of effort. Failure refines your approach, strengthens your mindset, and prepares you for success. Instead of hiding from mistakes, study them. Each failure brings a lesson that success can’t teach. Embrace it, learn from it, and keep moving forward with courage and clarity.`
];
