const   sampleNotificatios = [
  {
    id: 1,
    title: "Service Booked",
    message: "You have successfully booked a plumber for tomorrow.",
    time: "2025-08-05T11:10:00",
    read: false,
  },
  {
    id: 2,
    title: "New Message",
    message: "Your service partner has sent a message.",
    time: "2025-08-05T10:50:00",
    read: false,
  },
  {
    id: 3,
    title: "Payment Successful",
    message: "You paid ₹500 for Electrician service.",
    time: "2025-08-05T10:00:00",
    read: true,
  },
  {
    id: 4,
    title: "Reminder",
    message: "Your AC Service is scheduled for today at 5 PM.",
    time: "2025-08-04T21:00:00",
    read: true,
  },
  {
    id: 5,
    title: "Offer Unlocked",
    message: "Get 20% off on your next cleaning service.",
    time: "2025-08-04T17:45:00",
    read: false,
  },
  {
    id: 6,
    title: "Service Completed",
    message: "The Plumbing service has been marked complete.",
    time: "2025-08-04T13:30:00",
    read: true,
  },
  {
    id: 7,
    title: "Partner Assigned",
    message: "Rahul (Electrician) has been assigned to your request.",
    time: "2025-08-04T09:20:00",
    read: false,
  },
  {
    id: 8,
    title: "Invoice Generated",
    message: "Your invoice for Kitchen Cleaning is ready to download.",
    time: "2025-08-03T19:55:00",
    read: true,
  },
  {
    id: 9,
    title: "Account Update",
    message: "Your email address has been updated successfully.",
    time: "2025-08-03T14:40:00",
    read: true,
  },
  {
    id: 10,
    title: "Security Alert",
    message: "New login detected from Chrome browser.",
    time: "2025-08-03T08:15:00",
    read: false,
  },
  {
    id: 11,
    title: "New Review",
    message: "You received a 5-star review from a customer.",
    time: "2025-08-02T20:20:00",
    read: false,
  },
  {
    id: 12,
    title: "Slot Rescheduled",
    message: "Your AC repair slot has been moved to 6 PM.",
    time: "2025-08-02T16:10:00",
    read: false,
  },
  {
    id: 13,
    title: "Referral Earned",
    message: "You earned ₹100 for referring your friend.",
    time: "2025-08-02T11:30:00",
    read: false,
  },
  {
    id: 14,
    title: "Subscription Expired",
    message: "Your EaseHome Prime subscription has ended.",
    time: "2025-08-01T18:00:00",
    read: false,
  },
  {
    id: 15,
    title: "Update Available",
    message: "New features have been added to your dashboard.",
    time: "2025-08-01T09:00:00",
    read: false,
  },
];


export default sampleNotificatios;